server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker #branch
          uri: https://github.com/figonzal1/curso-ms-spring.git
          search-paths: config-data
  application:
    name: config-ms
